/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface AnalyticsSummary {
  'totalUniqueUsers' : bigint,
  'dailyActiveUsers' : bigint,
  'analyticsTrackingEnabled' : boolean,
  'lastActiveUsers' : bigint,
  'totalSessions' : bigint,
  'recentEvents' : Array<UsageEvent>,
}
export type EventType = { 'page_view' : null } |
  { 'action' : null } |
  { 'session_start' : null } |
  { 'logout' : null } |
  { 'login' : null };
export type ExternalBlob = Uint8Array;
export interface Gig {
  'id' : GigId,
  'status' : { 'pending' : null } |
    { 'completed' : null } |
    { 'confirmed' : null },
  'venueId' : UserId,
  'blob' : ExternalBlob,
  'date' : Time,
  'name' : string,
  'musicianId' : UserId,
  'contractUrl' : string,
  'price' : bigint,
}
export type GigId = bigint;
export type Role = { 'musician' : null } |
  { 'customer' : null } |
  { 'venue' : null };
export interface Slot {
  'id' : bigint,
  'startTime' : Time,
  'endTime' : [] | [Time],
  'userId' : UserId,
  'isAvailable' : boolean,
}
export type Time = bigint;
export interface UsageEvent {
  'principal' : Principal,
  'page' : [] | [string],
  'timestamp' : Time,
  'actionDetail' : [] | [string],
  'actionCategory' : [] | [string],
  'eventType' : EventType,
}
export type UserId = Principal;
export interface UserProfile {
  'id' : UserId,
  'bio' : string,
  'contractBlob' : [] | [ExternalBlob],
  'name' : string,
  'role' : Role,
  'rating' : number,
  'phone' : string,
  'location' : string,
}
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _CaffeineStorageCreateCertificateResult {
  'method' : string,
  'blob_hash' : string,
}
export interface _CaffeineStorageRefillInformation {
  'proposed_top_up_amount' : [] | [bigint],
}
export interface _CaffeineStorageRefillResult {
  'success' : [] | [boolean],
  'topped_up_amount' : [] | [bigint],
}
export interface _SERVICE {
  '_caffeineStorageBlobIsLive' : ActorMethod<[Uint8Array], boolean>,
  '_caffeineStorageBlobsToDelete' : ActorMethod<[], Array<Uint8Array>>,
  '_caffeineStorageConfirmBlobDeletion' : ActorMethod<
    [Array<Uint8Array>],
    undefined
  >,
  '_caffeineStorageCreateCertificate' : ActorMethod<
    [string],
    _CaffeineStorageCreateCertificateResult
  >,
  '_caffeineStorageRefillCashier' : ActorMethod<
    [[] | [_CaffeineStorageRefillInformation]],
    _CaffeineStorageRefillResult
  >,
  '_caffeineStorageUpdateGatewayPrincipals' : ActorMethod<[], undefined>,
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'bookGig' : ActorMethod<[Gig], undefined>,
  'clearAnalyticsData' : ActorMethod<[], undefined>,
  'createOrUpdateProfile' : ActorMethod<[UserProfile], undefined>,
  'createSlot' : ActorMethod<[Slot], undefined>,
  'disableAnalyticsTracking' : ActorMethod<[], undefined>,
  'enableAnalyticsTracking' : ActorMethod<[], undefined>,
  'fetchAllGigs' : ActorMethod<[], Array<Gig>>,
  'fetchAllMusicians' : ActorMethod<[], Array<UserProfile>>,
  'fetchAllProfiles' : ActorMethod<[], Array<UserProfile>>,
  'fetchAllSlots' : ActorMethod<[], Array<Slot>>,
  'fetchAvailableSlots' : ActorMethod<[UserId], Array<Slot>>,
  'fetchAvailableSlotsByMusician' : ActorMethod<[UserId], Array<Slot>>,
  'fetchGigs' : ActorMethod<[], Array<Gig>>,
  'fetchGigsByMusician' : ActorMethod<[UserId], Array<Gig>>,
  'fetchGigsByVenue' : ActorMethod<[UserId], Array<Gig>>,
  'fetchMusicianGigs' : ActorMethod<[UserId], Array<Gig>>,
  'fetchMusiciansByLocation' : ActorMethod<[string], Array<UserProfile>>,
  'fetchProfilesByLocation' : ActorMethod<[string], Array<UserProfile>>,
  'fetchSlots' : ActorMethod<[UserId], Array<Slot>>,
  'fetchSlotsByMusician' : ActorMethod<[UserId], Array<Slot>>,
  'fetchVenueGigs' : ActorMethod<[UserId], Array<Gig>>,
  'getAnalyticsSummary' : ActorMethod<[], AnalyticsSummary>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getUsageEvents' : ActorMethod<[], Array<UsageEvent>>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'getWalletState' : ActorMethod<
    [UserId],
    { 'paid' : bigint, 'locked' : bigint, 'available' : bigint }
  >,
  'isAnalyticsTrackingEnabled' : ActorMethod<[], boolean>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'recordUsageEvent' : ActorMethod<
    [EventType, [] | [string], [] | [string], [] | [string]],
    undefined
  >,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'updateSlotAvailability' : ActorMethod<[bigint, boolean], undefined>,
  'uploadContract' : ActorMethod<[bigint, string, ExternalBlob], undefined>,
  'verifyGig' : ActorMethod<[bigint], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];