/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const _CaffeineStorageCreateCertificateResult = IDL.Record({
  'method' : IDL.Text,
  'blob_hash' : IDL.Text,
});
export const _CaffeineStorageRefillInformation = IDL.Record({
  'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
});
export const _CaffeineStorageRefillResult = IDL.Record({
  'success' : IDL.Opt(IDL.Bool),
  'topped_up_amount' : IDL.Opt(IDL.Nat),
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const GigId = IDL.Nat;
export const UserId = IDL.Principal;
export const ExternalBlob = IDL.Vec(IDL.Nat8);
export const Time = IDL.Int;
export const Gig = IDL.Record({
  'id' : GigId,
  'status' : IDL.Variant({
    'pending' : IDL.Null,
    'completed' : IDL.Null,
    'confirmed' : IDL.Null,
  }),
  'venueId' : UserId,
  'blob' : ExternalBlob,
  'date' : Time,
  'name' : IDL.Text,
  'musicianId' : UserId,
  'contractUrl' : IDL.Text,
  'price' : IDL.Nat,
});
export const Role = IDL.Variant({
  'musician' : IDL.Null,
  'customer' : IDL.Null,
  'venue' : IDL.Null,
});
export const UserProfile = IDL.Record({
  'id' : UserId,
  'bio' : IDL.Text,
  'contractBlob' : IDL.Opt(ExternalBlob),
  'name' : IDL.Text,
  'role' : Role,
  'rating' : IDL.Float64,
  'phone' : IDL.Text,
  'location' : IDL.Text,
});
export const Slot = IDL.Record({
  'id' : IDL.Nat,
  'startTime' : Time,
  'endTime' : IDL.Opt(Time),
  'userId' : UserId,
  'isAvailable' : IDL.Bool,
});

export const idlService = IDL.Service({
  '_caffeineStorageBlobIsLive' : IDL.Func(
      [IDL.Vec(IDL.Nat8)],
      [IDL.Bool],
      ['query'],
    ),
  '_caffeineStorageBlobsToDelete' : IDL.Func(
      [],
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      ['query'],
    ),
  '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [],
      [],
    ),
  '_caffeineStorageCreateCertificate' : IDL.Func(
      [IDL.Text],
      [_CaffeineStorageCreateCertificateResult],
      [],
    ),
  '_caffeineStorageRefillCashier' : IDL.Func(
      [IDL.Opt(_CaffeineStorageRefillInformation)],
      [_CaffeineStorageRefillResult],
      [],
    ),
  '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'bookGig' : IDL.Func([Gig], [], []),
  'createOrUpdateProfile' : IDL.Func([UserProfile], [], []),
  'createSlot' : IDL.Func([Slot], [], []),
  'fetchAllGigs' : IDL.Func([], [IDL.Vec(Gig)], ['query']),
  'fetchAllMusicians' : IDL.Func([], [IDL.Vec(UserProfile)], ['query']),
  'fetchAllProfiles' : IDL.Func([], [IDL.Vec(UserProfile)], ['query']),
  'fetchAllSlots' : IDL.Func([], [IDL.Vec(Slot)], ['query']),
  'fetchAvailableSlots' : IDL.Func([UserId], [IDL.Vec(Slot)], ['query']),
  'fetchAvailableSlotsByMusician' : IDL.Func(
      [UserId],
      [IDL.Vec(Slot)],
      ['query'],
    ),
  'fetchGigs' : IDL.Func([], [IDL.Vec(Gig)], ['query']),
  'fetchGigsByMusician' : IDL.Func([UserId], [IDL.Vec(Gig)], ['query']),
  'fetchGigsByVenue' : IDL.Func([UserId], [IDL.Vec(Gig)], ['query']),
  'fetchMusicianGigs' : IDL.Func([UserId], [IDL.Vec(Gig)], ['query']),
  'fetchMusiciansByLocation' : IDL.Func(
      [IDL.Text],
      [IDL.Vec(UserProfile)],
      ['query'],
    ),
  'fetchProfilesByLocation' : IDL.Func(
      [IDL.Text],
      [IDL.Vec(UserProfile)],
      ['query'],
    ),
  'fetchSlots' : IDL.Func([UserId], [IDL.Vec(Slot)], ['query']),
  'fetchSlotsByMusician' : IDL.Func([UserId], [IDL.Vec(Slot)], ['query']),
  'fetchVenueGigs' : IDL.Func([UserId], [IDL.Vec(Gig)], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'getWalletState' : IDL.Func(
      [UserId],
      [
        IDL.Record({
          'paid' : IDL.Nat,
          'locked' : IDL.Nat,
          'available' : IDL.Nat,
        }),
      ],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'updateSlotAvailability' : IDL.Func([IDL.Nat, IDL.Bool], [], []),
  'uploadContract' : IDL.Func([IDL.Nat, IDL.Text, ExternalBlob], [], []),
  'verifyGig' : IDL.Func([IDL.Nat], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const _CaffeineStorageCreateCertificateResult = IDL.Record({
    'method' : IDL.Text,
    'blob_hash' : IDL.Text,
  });
  const _CaffeineStorageRefillInformation = IDL.Record({
    'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
  });
  const _CaffeineStorageRefillResult = IDL.Record({
    'success' : IDL.Opt(IDL.Bool),
    'topped_up_amount' : IDL.Opt(IDL.Nat),
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const GigId = IDL.Nat;
  const UserId = IDL.Principal;
  const ExternalBlob = IDL.Vec(IDL.Nat8);
  const Time = IDL.Int;
  const Gig = IDL.Record({
    'id' : GigId,
    'status' : IDL.Variant({
      'pending' : IDL.Null,
      'completed' : IDL.Null,
      'confirmed' : IDL.Null,
    }),
    'venueId' : UserId,
    'blob' : ExternalBlob,
    'date' : Time,
    'name' : IDL.Text,
    'musicianId' : UserId,
    'contractUrl' : IDL.Text,
    'price' : IDL.Nat,
  });
  const Role = IDL.Variant({
    'musician' : IDL.Null,
    'customer' : IDL.Null,
    'venue' : IDL.Null,
  });
  const UserProfile = IDL.Record({
    'id' : UserId,
    'bio' : IDL.Text,
    'contractBlob' : IDL.Opt(ExternalBlob),
    'name' : IDL.Text,
    'role' : Role,
    'rating' : IDL.Float64,
    'phone' : IDL.Text,
    'location' : IDL.Text,
  });
  const Slot = IDL.Record({
    'id' : IDL.Nat,
    'startTime' : Time,
    'endTime' : IDL.Opt(Time),
    'userId' : UserId,
    'isAvailable' : IDL.Bool,
  });
  
  return IDL.Service({
    '_caffeineStorageBlobIsLive' : IDL.Func(
        [IDL.Vec(IDL.Nat8)],
        [IDL.Bool],
        ['query'],
      ),
    '_caffeineStorageBlobsToDelete' : IDL.Func(
        [],
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        ['query'],
      ),
    '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [],
        [],
      ),
    '_caffeineStorageCreateCertificate' : IDL.Func(
        [IDL.Text],
        [_CaffeineStorageCreateCertificateResult],
        [],
      ),
    '_caffeineStorageRefillCashier' : IDL.Func(
        [IDL.Opt(_CaffeineStorageRefillInformation)],
        [_CaffeineStorageRefillResult],
        [],
      ),
    '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'bookGig' : IDL.Func([Gig], [], []),
    'createOrUpdateProfile' : IDL.Func([UserProfile], [], []),
    'createSlot' : IDL.Func([Slot], [], []),
    'fetchAllGigs' : IDL.Func([], [IDL.Vec(Gig)], ['query']),
    'fetchAllMusicians' : IDL.Func([], [IDL.Vec(UserProfile)], ['query']),
    'fetchAllProfiles' : IDL.Func([], [IDL.Vec(UserProfile)], ['query']),
    'fetchAllSlots' : IDL.Func([], [IDL.Vec(Slot)], ['query']),
    'fetchAvailableSlots' : IDL.Func([UserId], [IDL.Vec(Slot)], ['query']),
    'fetchAvailableSlotsByMusician' : IDL.Func(
        [UserId],
        [IDL.Vec(Slot)],
        ['query'],
      ),
    'fetchGigs' : IDL.Func([], [IDL.Vec(Gig)], ['query']),
    'fetchGigsByMusician' : IDL.Func([UserId], [IDL.Vec(Gig)], ['query']),
    'fetchGigsByVenue' : IDL.Func([UserId], [IDL.Vec(Gig)], ['query']),
    'fetchMusicianGigs' : IDL.Func([UserId], [IDL.Vec(Gig)], ['query']),
    'fetchMusiciansByLocation' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(UserProfile)],
        ['query'],
      ),
    'fetchProfilesByLocation' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(UserProfile)],
        ['query'],
      ),
    'fetchSlots' : IDL.Func([UserId], [IDL.Vec(Slot)], ['query']),
    'fetchSlotsByMusician' : IDL.Func([UserId], [IDL.Vec(Slot)], ['query']),
    'fetchVenueGigs' : IDL.Func([UserId], [IDL.Vec(Gig)], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'getWalletState' : IDL.Func(
        [UserId],
        [
          IDL.Record({
            'paid' : IDL.Nat,
            'locked' : IDL.Nat,
            'available' : IDL.Nat,
          }),
        ],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'updateSlotAvailability' : IDL.Func([IDL.Nat, IDL.Bool], [], []),
    'uploadContract' : IDL.Func([IDL.Nat, IDL.Text, ExternalBlob], [], []),
    'verifyGig' : IDL.Func([IDL.Nat], [], []),
  });
};

export const init = ({ IDL }) => { return []; };