/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export type GigId = bigint;
export interface AnalyticsSummary {
    totalUniqueUsers: bigint;
    dailyActiveUsers: bigint;
    analyticsTrackingEnabled: boolean;
    lastActiveUsers: bigint;
    totalSessions: bigint;
    recentEvents: Array<UsageEvent>;
}
export type Time = bigint;
export interface _CaffeineStorageRefillInformation {
    proposed_top_up_amount?: bigint;
}
export interface _CaffeineStorageCreateCertificateResult {
    method: string;
    blob_hash: string;
}
export type UserId = Principal;
export interface Gig {
    id: GigId;
    status: Variant_pending_completed_confirmed;
    venueId: UserId;
    blob: ExternalBlob;
    date: Time;
    name: string;
    musicianId: UserId;
    contractUrl: string;
    price: bigint;
}
export interface Slot {
    id: bigint;
    startTime: Time;
    endTime?: Time;
    userId: UserId;
    isAvailable: boolean;
}
export interface UsageEvent {
    principal: Principal;
    page?: string;
    timestamp: Time;
    actionDetail?: string;
    actionCategory?: string;
    eventType: EventType;
}
export interface UserProfile {
    id: UserId;
    bio: string;
    contractBlob?: ExternalBlob;
    name: string;
    role: Role;
    rating: number;
    phone: string;
    location: string;
}
export interface _CaffeineStorageRefillResult {
    success?: boolean;
    topped_up_amount?: bigint;
}
export enum EventType {
    page_view = "page_view",
    action = "action",
    session_start = "session_start",
    logout = "logout",
    login = "login"
}
export enum Role {
    musician = "musician",
    customer = "customer",
    venue = "venue"
}
export enum UserRole {
    admin = "admin",
    user = "user",
    guest = "guest"
}
export enum Variant_pending_completed_confirmed {
    pending = "pending",
    completed = "completed",
    confirmed = "confirmed"
}
export interface backendInterface {
    _caffeineStorageBlobIsLive(hash: Uint8Array): Promise<boolean>;
    _caffeineStorageBlobsToDelete(): Promise<Array<Uint8Array>>;
    _caffeineStorageConfirmBlobDeletion(blobs: Array<Uint8Array>): Promise<void>;
    _caffeineStorageCreateCertificate(blobHash: string): Promise<_CaffeineStorageCreateCertificateResult>;
    _caffeineStorageRefillCashier(refillInformation: _CaffeineStorageRefillInformation | null): Promise<_CaffeineStorageRefillResult>;
    _caffeineStorageUpdateGatewayPrincipals(): Promise<void>;
    _initializeAccessControlWithSecret(userSecret: string): Promise<void>;
    assignCallerUserRole(user: Principal, role: UserRole): Promise<void>;
    bookGig(gig: Gig): Promise<void>;
    clearAnalyticsData(): Promise<void>;
    createOrUpdateProfile(profile: UserProfile): Promise<void>;
    createSlot(slot: Slot): Promise<void>;
    disableAnalyticsTracking(): Promise<void>;
    enableAnalyticsTracking(): Promise<void>;
    fetchAllGigs(): Promise<Array<Gig>>;
    fetchAllMusicians(): Promise<Array<UserProfile>>;
    fetchAllProfiles(): Promise<Array<UserProfile>>;
    fetchAllSlots(): Promise<Array<Slot>>;
    fetchAvailableSlots(userId: UserId): Promise<Array<Slot>>;
    fetchAvailableSlotsByMusician(musicianId: UserId): Promise<Array<Slot>>;
    fetchGigs(): Promise<Array<Gig>>;
    fetchGigsByMusician(musicianId: UserId): Promise<Array<Gig>>;
    fetchGigsByVenue(venueId: UserId): Promise<Array<Gig>>;
    fetchMusicianGigs(userId: UserId): Promise<Array<Gig>>;
    fetchMusiciansByLocation(location: string): Promise<Array<UserProfile>>;
    fetchProfilesByLocation(location: string): Promise<Array<UserProfile>>;
    fetchSlots(userId: UserId): Promise<Array<Slot>>;
    fetchSlotsByMusician(musicianId: UserId): Promise<Array<Slot>>;
    fetchVenueGigs(userId: UserId): Promise<Array<Gig>>;
    getAnalyticsSummary(): Promise<AnalyticsSummary>;
    getCallerUserProfile(): Promise<UserProfile | null>;
    getCallerUserRole(): Promise<UserRole>;
    getUsageEvents(): Promise<Array<UsageEvent>>;
    getUserProfile(user: Principal): Promise<UserProfile | null>;
    getWalletState(userId: UserId): Promise<{
        paid: bigint;
        locked: bigint;
        available: bigint;
    }>;
    isAnalyticsTrackingEnabled(): Promise<boolean>;
    isCallerAdmin(): Promise<boolean>;
    recordUsageEvent(eventType: EventType, page: string | null, actionCategory: string | null, actionDetail: string | null): Promise<void>;
    saveCallerUserProfile(profile: UserProfile): Promise<void>;
    updateSlotAvailability(slotId: bigint, available: boolean): Promise<void>;
    uploadContract(gigId: bigint, blobId: string, contract: ExternalBlob): Promise<void>;
    verifyGig(gigId: bigint): Promise<void>;
}
import type { AnalyticsSummary as _AnalyticsSummary, EventType as _EventType, ExternalBlob as _ExternalBlob, Gig as _Gig, GigId as _GigId, Role as _Role, Slot as _Slot, Time as _Time, UsageEvent as _UsageEvent, UserId as _UserId, UserProfile as _UserProfile, UserRole as _UserRole, _CaffeineStorageRefillInformation as __CaffeineStorageRefillInformation, _CaffeineStorageRefillResult as __CaffeineStorageRefillResult } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async _caffeineStorageBlobIsLive(arg0: Uint8Array): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageBlobIsLive(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageBlobIsLive(arg0);
            return result;
        }
    }
    async _caffeineStorageBlobsToDelete(): Promise<Array<Uint8Array>> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageBlobsToDelete();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageBlobsToDelete();
            return result;
        }
    }
    async _caffeineStorageConfirmBlobDeletion(arg0: Array<Uint8Array>): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageConfirmBlobDeletion(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageConfirmBlobDeletion(arg0);
            return result;
        }
    }
    async _caffeineStorageCreateCertificate(arg0: string): Promise<_CaffeineStorageCreateCertificateResult> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageCreateCertificate(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageCreateCertificate(arg0);
            return result;
        }
    }
    async _caffeineStorageRefillCashier(arg0: _CaffeineStorageRefillInformation | null): Promise<_CaffeineStorageRefillResult> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageRefillCashier(to_candid_opt_n1(this._uploadFile, this._downloadFile, arg0));
                return from_candid__CaffeineStorageRefillResult_n4(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageRefillCashier(to_candid_opt_n1(this._uploadFile, this._downloadFile, arg0));
            return from_candid__CaffeineStorageRefillResult_n4(this._uploadFile, this._downloadFile, result);
        }
    }
    async _caffeineStorageUpdateGatewayPrincipals(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageUpdateGatewayPrincipals();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageUpdateGatewayPrincipals();
            return result;
        }
    }
    async _initializeAccessControlWithSecret(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._initializeAccessControlWithSecret(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._initializeAccessControlWithSecret(arg0);
            return result;
        }
    }
    async assignCallerUserRole(arg0: Principal, arg1: UserRole): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n8(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n8(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async bookGig(arg0: Gig): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.bookGig(await to_candid_Gig_n10(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.bookGig(await to_candid_Gig_n10(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async clearAnalyticsData(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.clearAnalyticsData();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.clearAnalyticsData();
            return result;
        }
    }
    async createOrUpdateProfile(arg0: UserProfile): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.createOrUpdateProfile(await to_candid_UserProfile_n14(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createOrUpdateProfile(await to_candid_UserProfile_n14(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async createSlot(arg0: Slot): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.createSlot(to_candid_Slot_n18(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createSlot(to_candid_Slot_n18(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async disableAnalyticsTracking(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.disableAnalyticsTracking();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.disableAnalyticsTracking();
            return result;
        }
    }
    async enableAnalyticsTracking(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.enableAnalyticsTracking();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.enableAnalyticsTracking();
            return result;
        }
    }
    async fetchAllGigs(): Promise<Array<Gig>> {
        if (this.processError) {
            try {
                const result = await this.actor.fetchAllGigs();
                return from_candid_vec_n20(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.fetchAllGigs();
            return from_candid_vec_n20(this._uploadFile, this._downloadFile, result);
        }
    }
    async fetchAllMusicians(): Promise<Array<UserProfile>> {
        if (this.processError) {
            try {
                const result = await this.actor.fetchAllMusicians();
                return from_candid_vec_n25(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.fetchAllMusicians();
            return from_candid_vec_n25(this._uploadFile, this._downloadFile, result);
        }
    }
    async fetchAllProfiles(): Promise<Array<UserProfile>> {
        if (this.processError) {
            try {
                const result = await this.actor.fetchAllProfiles();
                return from_candid_vec_n25(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.fetchAllProfiles();
            return from_candid_vec_n25(this._uploadFile, this._downloadFile, result);
        }
    }
    async fetchAllSlots(): Promise<Array<Slot>> {
        if (this.processError) {
            try {
                const result = await this.actor.fetchAllSlots();
                return from_candid_vec_n31(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.fetchAllSlots();
            return from_candid_vec_n31(this._uploadFile, this._downloadFile, result);
        }
    }
    async fetchAvailableSlots(arg0: UserId): Promise<Array<Slot>> {
        if (this.processError) {
            try {
                const result = await this.actor.fetchAvailableSlots(arg0);
                return from_candid_vec_n31(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.fetchAvailableSlots(arg0);
            return from_candid_vec_n31(this._uploadFile, this._downloadFile, result);
        }
    }
    async fetchAvailableSlotsByMusician(arg0: UserId): Promise<Array<Slot>> {
        if (this.processError) {
            try {
                const result = await this.actor.fetchAvailableSlotsByMusician(arg0);
                return from_candid_vec_n31(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.fetchAvailableSlotsByMusician(arg0);
            return from_candid_vec_n31(this._uploadFile, this._downloadFile, result);
        }
    }
    async fetchGigs(): Promise<Array<Gig>> {
        if (this.processError) {
            try {
                const result = await this.actor.fetchGigs();
                return from_candid_vec_n20(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.fetchGigs();
            return from_candid_vec_n20(this._uploadFile, this._downloadFile, result);
        }
    }
    async fetchGigsByMusician(arg0: UserId): Promise<Array<Gig>> {
        if (this.processError) {
            try {
                const result = await this.actor.fetchGigsByMusician(arg0);
                return from_candid_vec_n20(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.fetchGigsByMusician(arg0);
            return from_candid_vec_n20(this._uploadFile, this._downloadFile, result);
        }
    }
    async fetchGigsByVenue(arg0: UserId): Promise<Array<Gig>> {
        if (this.processError) {
            try {
                const result = await this.actor.fetchGigsByVenue(arg0);
                return from_candid_vec_n20(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.fetchGigsByVenue(arg0);
            return from_candid_vec_n20(this._uploadFile, this._downloadFile, result);
        }
    }
    async fetchMusicianGigs(arg0: UserId): Promise<Array<Gig>> {
        if (this.processError) {
            try {
                const result = await this.actor.fetchMusicianGigs(arg0);
                return from_candid_vec_n20(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.fetchMusicianGigs(arg0);
            return from_candid_vec_n20(this._uploadFile, this._downloadFile, result);
        }
    }
    async fetchMusiciansByLocation(arg0: string): Promise<Array<UserProfile>> {
        if (this.processError) {
            try {
                const result = await this.actor.fetchMusiciansByLocation(arg0);
                return from_candid_vec_n25(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.fetchMusiciansByLocation(arg0);
            return from_candid_vec_n25(this._uploadFile, this._downloadFile, result);
        }
    }
    async fetchProfilesByLocation(arg0: string): Promise<Array<UserProfile>> {
        if (this.processError) {
            try {
                const result = await this.actor.fetchProfilesByLocation(arg0);
                return from_candid_vec_n25(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.fetchProfilesByLocation(arg0);
            return from_candid_vec_n25(this._uploadFile, this._downloadFile, result);
        }
    }
    async fetchSlots(arg0: UserId): Promise<Array<Slot>> {
        if (this.processError) {
            try {
                const result = await this.actor.fetchSlots(arg0);
                return from_candid_vec_n31(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.fetchSlots(arg0);
            return from_candid_vec_n31(this._uploadFile, this._downloadFile, result);
        }
    }
    async fetchSlotsByMusician(arg0: UserId): Promise<Array<Slot>> {
        if (this.processError) {
            try {
                const result = await this.actor.fetchSlotsByMusician(arg0);
                return from_candid_vec_n31(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.fetchSlotsByMusician(arg0);
            return from_candid_vec_n31(this._uploadFile, this._downloadFile, result);
        }
    }
    async fetchVenueGigs(arg0: UserId): Promise<Array<Gig>> {
        if (this.processError) {
            try {
                const result = await this.actor.fetchVenueGigs(arg0);
                return from_candid_vec_n20(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.fetchVenueGigs(arg0);
            return from_candid_vec_n20(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAnalyticsSummary(): Promise<AnalyticsSummary> {
        if (this.processError) {
            try {
                const result = await this.actor.getAnalyticsSummary();
                return from_candid_AnalyticsSummary_n35(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAnalyticsSummary();
            return from_candid_AnalyticsSummary_n35(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserProfile(): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserProfile();
                return from_candid_opt_n43(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserProfile();
            return from_candid_opt_n43(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserRole(): Promise<UserRole> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserRole();
                return from_candid_UserRole_n44(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserRole();
            return from_candid_UserRole_n44(this._uploadFile, this._downloadFile, result);
        }
    }
    async getUsageEvents(): Promise<Array<UsageEvent>> {
        if (this.processError) {
            try {
                const result = await this.actor.getUsageEvents();
                return from_candid_vec_n37(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUsageEvents();
            return from_candid_vec_n37(this._uploadFile, this._downloadFile, result);
        }
    }
    async getUserProfile(arg0: Principal): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserProfile(arg0);
                return from_candid_opt_n43(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserProfile(arg0);
            return from_candid_opt_n43(this._uploadFile, this._downloadFile, result);
        }
    }
    async getWalletState(arg0: UserId): Promise<{
        paid: bigint;
        locked: bigint;
        available: bigint;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.getWalletState(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getWalletState(arg0);
            return result;
        }
    }
    async isAnalyticsTrackingEnabled(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isAnalyticsTrackingEnabled();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isAnalyticsTrackingEnabled();
            return result;
        }
    }
    async isCallerAdmin(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isCallerAdmin();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isCallerAdmin();
            return result;
        }
    }
    async recordUsageEvent(arg0: EventType, arg1: string | null, arg2: string | null, arg3: string | null): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.recordUsageEvent(to_candid_EventType_n46(this._uploadFile, this._downloadFile, arg0), to_candid_opt_n48(this._uploadFile, this._downloadFile, arg1), to_candid_opt_n48(this._uploadFile, this._downloadFile, arg2), to_candid_opt_n48(this._uploadFile, this._downloadFile, arg3));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.recordUsageEvent(to_candid_EventType_n46(this._uploadFile, this._downloadFile, arg0), to_candid_opt_n48(this._uploadFile, this._downloadFile, arg1), to_candid_opt_n48(this._uploadFile, this._downloadFile, arg2), to_candid_opt_n48(this._uploadFile, this._downloadFile, arg3));
            return result;
        }
    }
    async saveCallerUserProfile(arg0: UserProfile): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.saveCallerUserProfile(await to_candid_UserProfile_n14(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveCallerUserProfile(await to_candid_UserProfile_n14(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async updateSlotAvailability(arg0: bigint, arg1: boolean): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateSlotAvailability(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateSlotAvailability(arg0, arg1);
            return result;
        }
    }
    async uploadContract(arg0: bigint, arg1: string, arg2: ExternalBlob): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.uploadContract(arg0, arg1, await to_candid_ExternalBlob_n13(this._uploadFile, this._downloadFile, arg2));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.uploadContract(arg0, arg1, await to_candid_ExternalBlob_n13(this._uploadFile, this._downloadFile, arg2));
            return result;
        }
    }
    async verifyGig(arg0: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.verifyGig(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.verifyGig(arg0);
            return result;
        }
    }
}
function from_candid_AnalyticsSummary_n35(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _AnalyticsSummary): AnalyticsSummary {
    return from_candid_record_n36(_uploadFile, _downloadFile, value);
}
function from_candid_EventType_n41(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _EventType): EventType {
    return from_candid_variant_n42(_uploadFile, _downloadFile, value);
}
async function from_candid_ExternalBlob_n24(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ExternalBlob): Promise<ExternalBlob> {
    return await _downloadFile(value);
}
async function from_candid_Gig_n21(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Gig): Promise<Gig> {
    return await from_candid_record_n22(_uploadFile, _downloadFile, value);
}
function from_candid_Role_n29(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Role): Role {
    return from_candid_variant_n30(_uploadFile, _downloadFile, value);
}
function from_candid_Slot_n32(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Slot): Slot {
    return from_candid_record_n33(_uploadFile, _downloadFile, value);
}
function from_candid_UsageEvent_n38(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UsageEvent): UsageEvent {
    return from_candid_record_n39(_uploadFile, _downloadFile, value);
}
async function from_candid_UserProfile_n26(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserProfile): Promise<UserProfile> {
    return await from_candid_record_n27(_uploadFile, _downloadFile, value);
}
function from_candid_UserRole_n44(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserRole): UserRole {
    return from_candid_variant_n45(_uploadFile, _downloadFile, value);
}
function from_candid__CaffeineStorageRefillResult_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: __CaffeineStorageRefillResult): _CaffeineStorageRefillResult {
    return from_candid_record_n5(_uploadFile, _downloadFile, value);
}
async function from_candid_opt_n28(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_ExternalBlob]): Promise<ExternalBlob | null> {
    return value.length === 0 ? null : await from_candid_ExternalBlob_n24(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n34(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Time]): Time | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n40(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [string]): string | null {
    return value.length === 0 ? null : value[0];
}
async function from_candid_opt_n43(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_UserProfile]): Promise<UserProfile | null> {
    return value.length === 0 ? null : await from_candid_UserProfile_n26(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [boolean]): boolean | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [bigint]): bigint | null {
    return value.length === 0 ? null : value[0];
}
async function from_candid_record_n22(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: _GigId;
    status: {
        pending: null;
    } | {
        completed: null;
    } | {
        confirmed: null;
    };
    venueId: _UserId;
    blob: _ExternalBlob;
    date: _Time;
    name: string;
    musicianId: _UserId;
    contractUrl: string;
    price: bigint;
}): Promise<{
    id: GigId;
    status: Variant_pending_completed_confirmed;
    venueId: UserId;
    blob: ExternalBlob;
    date: Time;
    name: string;
    musicianId: UserId;
    contractUrl: string;
    price: bigint;
}> {
    return {
        id: value.id,
        status: from_candid_variant_n23(_uploadFile, _downloadFile, value.status),
        venueId: value.venueId,
        blob: await from_candid_ExternalBlob_n24(_uploadFile, _downloadFile, value.blob),
        date: value.date,
        name: value.name,
        musicianId: value.musicianId,
        contractUrl: value.contractUrl,
        price: value.price
    };
}
async function from_candid_record_n27(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: _UserId;
    bio: string;
    contractBlob: [] | [_ExternalBlob];
    name: string;
    role: _Role;
    rating: number;
    phone: string;
    location: string;
}): Promise<{
    id: UserId;
    bio: string;
    contractBlob?: ExternalBlob;
    name: string;
    role: Role;
    rating: number;
    phone: string;
    location: string;
}> {
    return {
        id: value.id,
        bio: value.bio,
        contractBlob: record_opt_to_undefined(await from_candid_opt_n28(_uploadFile, _downloadFile, value.contractBlob)),
        name: value.name,
        role: from_candid_Role_n29(_uploadFile, _downloadFile, value.role),
        rating: value.rating,
        phone: value.phone,
        location: value.location
    };
}
function from_candid_record_n33(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    startTime: _Time;
    endTime: [] | [_Time];
    userId: _UserId;
    isAvailable: boolean;
}): {
    id: bigint;
    startTime: Time;
    endTime?: Time;
    userId: UserId;
    isAvailable: boolean;
} {
    return {
        id: value.id,
        startTime: value.startTime,
        endTime: record_opt_to_undefined(from_candid_opt_n34(_uploadFile, _downloadFile, value.endTime)),
        userId: value.userId,
        isAvailable: value.isAvailable
    };
}
function from_candid_record_n36(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    totalUniqueUsers: bigint;
    dailyActiveUsers: bigint;
    analyticsTrackingEnabled: boolean;
    lastActiveUsers: bigint;
    totalSessions: bigint;
    recentEvents: Array<_UsageEvent>;
}): {
    totalUniqueUsers: bigint;
    dailyActiveUsers: bigint;
    analyticsTrackingEnabled: boolean;
    lastActiveUsers: bigint;
    totalSessions: bigint;
    recentEvents: Array<UsageEvent>;
} {
    return {
        totalUniqueUsers: value.totalUniqueUsers,
        dailyActiveUsers: value.dailyActiveUsers,
        analyticsTrackingEnabled: value.analyticsTrackingEnabled,
        lastActiveUsers: value.lastActiveUsers,
        totalSessions: value.totalSessions,
        recentEvents: from_candid_vec_n37(_uploadFile, _downloadFile, value.recentEvents)
    };
}
function from_candid_record_n39(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    principal: Principal;
    page: [] | [string];
    timestamp: _Time;
    actionDetail: [] | [string];
    actionCategory: [] | [string];
    eventType: _EventType;
}): {
    principal: Principal;
    page?: string;
    timestamp: Time;
    actionDetail?: string;
    actionCategory?: string;
    eventType: EventType;
} {
    return {
        principal: value.principal,
        page: record_opt_to_undefined(from_candid_opt_n40(_uploadFile, _downloadFile, value.page)),
        timestamp: value.timestamp,
        actionDetail: record_opt_to_undefined(from_candid_opt_n40(_uploadFile, _downloadFile, value.actionDetail)),
        actionCategory: record_opt_to_undefined(from_candid_opt_n40(_uploadFile, _downloadFile, value.actionCategory)),
        eventType: from_candid_EventType_n41(_uploadFile, _downloadFile, value.eventType)
    };
}
function from_candid_record_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    success: [] | [boolean];
    topped_up_amount: [] | [bigint];
}): {
    success?: boolean;
    topped_up_amount?: bigint;
} {
    return {
        success: record_opt_to_undefined(from_candid_opt_n6(_uploadFile, _downloadFile, value.success)),
        topped_up_amount: record_opt_to_undefined(from_candid_opt_n7(_uploadFile, _downloadFile, value.topped_up_amount))
    };
}
function from_candid_variant_n23(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    pending: null;
} | {
    completed: null;
} | {
    confirmed: null;
}): Variant_pending_completed_confirmed {
    return "pending" in value ? Variant_pending_completed_confirmed.pending : "completed" in value ? Variant_pending_completed_confirmed.completed : "confirmed" in value ? Variant_pending_completed_confirmed.confirmed : value;
}
function from_candid_variant_n30(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    musician: null;
} | {
    customer: null;
} | {
    venue: null;
}): Role {
    return "musician" in value ? Role.musician : "customer" in value ? Role.customer : "venue" in value ? Role.venue : value;
}
function from_candid_variant_n42(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    page_view: null;
} | {
    action: null;
} | {
    session_start: null;
} | {
    logout: null;
} | {
    login: null;
}): EventType {
    return "page_view" in value ? EventType.page_view : "action" in value ? EventType.action : "session_start" in value ? EventType.session_start : "logout" in value ? EventType.logout : "login" in value ? EventType.login : value;
}
function from_candid_variant_n45(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
}): UserRole {
    return "admin" in value ? UserRole.admin : "user" in value ? UserRole.user : "guest" in value ? UserRole.guest : value;
}
async function from_candid_vec_n20(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Gig>): Promise<Array<Gig>> {
    return await Promise.all(value.map(async (x)=>await from_candid_Gig_n21(_uploadFile, _downloadFile, x)));
}
async function from_candid_vec_n25(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_UserProfile>): Promise<Array<UserProfile>> {
    return await Promise.all(value.map(async (x)=>await from_candid_UserProfile_n26(_uploadFile, _downloadFile, x)));
}
function from_candid_vec_n31(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Slot>): Array<Slot> {
    return value.map((x)=>from_candid_Slot_n32(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n37(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_UsageEvent>): Array<UsageEvent> {
    return value.map((x)=>from_candid_UsageEvent_n38(_uploadFile, _downloadFile, x));
}
function to_candid_EventType_n46(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: EventType): _EventType {
    return to_candid_variant_n47(_uploadFile, _downloadFile, value);
}
async function to_candid_ExternalBlob_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ExternalBlob): Promise<_ExternalBlob> {
    return await _uploadFile(value);
}
async function to_candid_Gig_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Gig): Promise<_Gig> {
    return await to_candid_record_n11(_uploadFile, _downloadFile, value);
}
function to_candid_Role_n16(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Role): _Role {
    return to_candid_variant_n17(_uploadFile, _downloadFile, value);
}
function to_candid_Slot_n18(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Slot): _Slot {
    return to_candid_record_n19(_uploadFile, _downloadFile, value);
}
async function to_candid_UserProfile_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserProfile): Promise<_UserProfile> {
    return await to_candid_record_n15(_uploadFile, _downloadFile, value);
}
function to_candid_UserRole_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): _UserRole {
    return to_candid_variant_n9(_uploadFile, _downloadFile, value);
}
function to_candid__CaffeineStorageRefillInformation_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _CaffeineStorageRefillInformation): __CaffeineStorageRefillInformation {
    return to_candid_record_n3(_uploadFile, _downloadFile, value);
}
function to_candid_opt_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _CaffeineStorageRefillInformation | null): [] | [__CaffeineStorageRefillInformation] {
    return value === null ? candid_none() : candid_some(to_candid__CaffeineStorageRefillInformation_n2(_uploadFile, _downloadFile, value));
}
function to_candid_opt_n48(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: string | null): [] | [string] {
    return value === null ? candid_none() : candid_some(value);
}
async function to_candid_record_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: GigId;
    status: Variant_pending_completed_confirmed;
    venueId: UserId;
    blob: ExternalBlob;
    date: Time;
    name: string;
    musicianId: UserId;
    contractUrl: string;
    price: bigint;
}): Promise<{
    id: _GigId;
    status: {
        pending: null;
    } | {
        completed: null;
    } | {
        confirmed: null;
    };
    venueId: _UserId;
    blob: _ExternalBlob;
    date: _Time;
    name: string;
    musicianId: _UserId;
    contractUrl: string;
    price: bigint;
}> {
    return {
        id: value.id,
        status: to_candid_variant_n12(_uploadFile, _downloadFile, value.status),
        venueId: value.venueId,
        blob: await to_candid_ExternalBlob_n13(_uploadFile, _downloadFile, value.blob),
        date: value.date,
        name: value.name,
        musicianId: value.musicianId,
        contractUrl: value.contractUrl,
        price: value.price
    };
}
async function to_candid_record_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: UserId;
    bio: string;
    contractBlob?: ExternalBlob;
    name: string;
    role: Role;
    rating: number;
    phone: string;
    location: string;
}): Promise<{
    id: _UserId;
    bio: string;
    contractBlob: [] | [_ExternalBlob];
    name: string;
    role: _Role;
    rating: number;
    phone: string;
    location: string;
}> {
    return {
        id: value.id,
        bio: value.bio,
        contractBlob: value.contractBlob ? candid_some(await to_candid_ExternalBlob_n13(_uploadFile, _downloadFile, value.contractBlob)) : candid_none(),
        name: value.name,
        role: to_candid_Role_n16(_uploadFile, _downloadFile, value.role),
        rating: value.rating,
        phone: value.phone,
        location: value.location
    };
}
function to_candid_record_n19(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    startTime: Time;
    endTime?: Time;
    userId: UserId;
    isAvailable: boolean;
}): {
    id: bigint;
    startTime: _Time;
    endTime: [] | [_Time];
    userId: _UserId;
    isAvailable: boolean;
} {
    return {
        id: value.id,
        startTime: value.startTime,
        endTime: value.endTime ? candid_some(value.endTime) : candid_none(),
        userId: value.userId,
        isAvailable: value.isAvailable
    };
}
function to_candid_record_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    proposed_top_up_amount?: bigint;
}): {
    proposed_top_up_amount: [] | [bigint];
} {
    return {
        proposed_top_up_amount: value.proposed_top_up_amount ? candid_some(value.proposed_top_up_amount) : candid_none()
    };
}
function to_candid_variant_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Variant_pending_completed_confirmed): {
    pending: null;
} | {
    completed: null;
} | {
    confirmed: null;
} {
    return value == Variant_pending_completed_confirmed.pending ? {
        pending: null
    } : value == Variant_pending_completed_confirmed.completed ? {
        completed: null
    } : value == Variant_pending_completed_confirmed.confirmed ? {
        confirmed: null
    } : value;
}
function to_candid_variant_n17(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Role): {
    musician: null;
} | {
    customer: null;
} | {
    venue: null;
} {
    return value == Role.musician ? {
        musician: null
    } : value == Role.customer ? {
        customer: null
    } : value == Role.venue ? {
        venue: null
    } : value;
}
function to_candid_variant_n47(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: EventType): {
    page_view: null;
} | {
    action: null;
} | {
    session_start: null;
} | {
    logout: null;
} | {
    login: null;
} {
    return value == EventType.page_view ? {
        page_view: null
    } : value == EventType.action ? {
        action: null
    } : value == EventType.session_start ? {
        session_start: null
    } : value == EventType.logout ? {
        logout: null
    } : value == EventType.login ? {
        login: null
    } : value;
}
function to_candid_variant_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
} {
    return value == UserRole.admin ? {
        admin: null
    } : value == UserRole.user ? {
        user: null
    } : value == UserRole.guest ? {
        guest: null
    } : value;
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
